#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  1 01:44:24 2020

@author: vaibhavpatel
"""


import json
import os, os.path
import pickle
import numpy as np
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf
import glob
import cv2
import imageio
import pickle
import sys